# Route mappings for different languages
default_routes:
  /: /
  /docs/: /docs/
  /docs/installation/: /docs/installation/
  /docs/quickstart/: /docs/quickstart/
  /docs/configuration/: /docs/configuration/
  /docs/routing/: /docs/routing/
  /docs/middleware/: /docs/middleware/
  /docs/requests-responses/: /docs/requests-responses/
  /docs/container/: /docs/container/
  /docs/security/: /docs/security/
  /docs/events/: /docs/events/
  /docs/validation/: /docs/validation/
  /docs/database/: /docs/database/
  /docs/providers/: /docs/providers/
  /docs/testing/: /docs/testing/
  /docs/deployment/: /docs/deployment/
  /docs/extensions/: /docs/extensions/
  /docs/extensions/cycle-orm/: /docs/extensions/cycle-orm/

pt_routes:
  /: /pt/
  /docs/: /pt/docs/
  /docs/installation/: /pt/docs/instalacao/
  /docs/quickstart/: /pt/docs/inicio-rapido/
  /docs/configuration/: /pt/docs/configuracao/
  /docs/routing/: /pt/docs/roteamento/
  /docs/middleware/: /pt/docs/middleware/
  /docs/requests-responses/: /pt/docs/requisicoes-respostas/
  /docs/container/: /pt/docs/container/
  /docs/security/: /pt/docs/seguranca/
  /docs/events/: /pt/docs/eventos/
  /docs/validation/: /pt/docs/validacao/
  /docs/database/: /pt/docs/banco-de-dados/
  /docs/providers/: /pt/docs/provedores/
  /docs/testing/: /pt/docs/testes/
  /docs/deployment/: /pt/docs/implantacao/
  /docs/extensions/: /pt/docs/extensions/
  /docs/extensions/cycle-orm/: /pt/docs/extensions/cycle-orm/

en:
  home: /
  docs: /docs/
  why_pivotphp: /docs/why-pivotphp/
  installation: /docs/installation/
  quickstart: /docs/quickstart/
  configuration: /docs/configuration/
  routing: /docs/routing/
  middleware: /docs/middleware/
  requests_responses: /docs/requests-responses/
  api_documentation: /docs/api-documentation/
  container: /docs/container/
  security: /docs/security/
  events: /docs/events/
  validation: /docs/validation/
  database: /docs/database/
  providers: /docs/providers/
  testing: /docs/testing/
  deployment: /docs/deployment/
  benchmarks: /docs/benchmarks/
  extensions: /docs/extensions/
  extensions_cycle_orm: /docs/extensions/cycle-orm/
  extensions_reactphp: /docs/extensions/reactphp/

pt:
  home: /pt/
  docs: /pt/docs/
  why_pivotphp: /pt/docs/why-pivotphp/
  installation: /pt/docs/installation/
  quickstart: /pt/docs/quickstart/
  configuration: /pt/docs/configuration/
  routing: /pt/docs/routing/
  middleware: /pt/docs/middleware/
  requests_responses: /pt/docs/requests-responses/
  api_documentation: /pt/docs/api-documentation/
  container: /pt/docs/container/
  security: /pt/docs/security/
  events: /pt/docs/events/
  validation: /pt/docs/validation/
  database: /pt/docs/database/
  providers: /pt/docs/providers/
  testing: /pt/docs/testing/
  deployment: /pt/docs/deployment/
  benchmarks: /pt/docs/benchmarks/
  extensions: /pt/docs/extensions/
  extensions_cycle_orm: /pt/docs/extensions/cycle-orm/
  extensions_reactphp: /pt/docs/extensions/reactphp/